// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplicationC.Data;

#nullable disable

namespace WebApplicationC_.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260820092552_AddDoctorTable")]
    partial class AddDoctorTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplicationC.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Hospital")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRecommended")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("ReviewsCount")
                        .HasColumnType("int");

                    b.Property<string>("Speciality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Hospital = "RSUD Gatot Subroto",
                            ImageUrl = "assets/images/doctor_randy.png",
                            IsRecommended = true,
                            Name = "Dr. Randy Wigham",
                            Rating = 4.7999999999999998,
                            ReviewsCount = 4279,
                            Speciality = "General"
                        },
                        new
                        {
                            Id = 2,
                            Hospital = "RSUD Gatot Subroto",
                            ImageUrl = "assets/images/doctor_sarah.png",
                            IsRecommended = true,
                            Name = "Dr. Sarah Sulivan",
                            Rating = 4.5999999999999996,
                            ReviewsCount = 3120,
                            Speciality = "Neurologic"
                        },
                        new
                        {
                            Id = 3,
                            Hospital = "Cairo General Hospital",
                            ImageUrl = "assets/images/doctor_amina.png",
                            IsRecommended = true,
                            Name = "Dr. Amina Farouk",
                            Rating = 4.9000000000000004,
                            ReviewsCount = 2894,
                            Speciality = "Pediatric"
                        });
                });

            modelBuilder.Entity("WebApplicationC.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
